### ISSUE TITLE
Unable to run amass-passive scan

### ISSUE THREAD

**Issue by Deathpoolxrs** [yogeshojha/rengine#1148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting Following error
rengine-celery-1       | subdomain_discovery                | ERROR | local variable 'use_amass_config' referenced before assignment
rengine-celery-1       | Traceback (most recent call last):
rengine-celery-1       |   File "/usr/src/app/reNgine/celery_custom_task.py", line 129, in __call__
rengine-celery-1       |     self.result = self.run(*args, **kwargs)
rengine-celery-1       |   File "/usr/src/app/reNgine/tasks.py", line 420, in subdomain_discovery
rengine-celery-1       |     cmd += ' -config /root/.config/amass.ini' if use_amass_config else ''
rengine-celery-1       | UnboundLocalError: local variable 'use_amass_config' referenced before assignment

### Expected Behavior

It should give subdomains after amass-passive scan

### Steps To Reproduce

Just run a subdomain scan with the following engine configurations 

```
subdomain_discovery: {
  'uses_tools': [
    'subfinder', 
    'ctfr', 
    'sublist3r', 
    'tlsx', 
    'oneforall', 
    'netlas',
    'amass-passive'
  ],
  'enable_http_crawl': true,
  'threads': 30,
  'timeout': 5,
}
http_crawl: {}
```

### Environment

```markdown
- reNgine: 2.0.2
```

**Comment by Deathpoolxrs** [comment]
### I have fixed this by adding the following line: 

The code use_amass_config = config.get(USE_AMASS_CONFIG, False) retrieves the value associated with the key USE_AMASS_CONFIG from a configuration dictionary (config). If the key is not found, it defaults to False. The variable use_amass_config is then assigned this value.
```
	# Run tools
	for tool in tools:
		cmd = None
		logger.info(f'Scanning subdomains for {host} with {tool}')
		proxy = get_random_proxy()
		if tool in default_subdomain_tools:
			if tool == 'amass-passive':
				use_amass_config = config.get(USE_AMASS_CONFIG, False)
				cmd = f'amass enum -passive -d {host} -o {self.results_dir}/subdomains_amass.txt'
				cmd += ' -config /root/.config/amass.ini' if use_amass_config else ''
```
