### ISSUE TITLE
bug: Rengine 2.03 Fresh Install BUG (reinstall) - uninstall.sh BUG (outdated) - #972 has reappeared on the scene

### ISSUE THREAD

**Issue by carboncrystal** [yogeshojha/rengine#1187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## uninstall.sh bug (outdated) - see line 14
`docker stop rengine_web_1 rengine_db_1 rengine_celery_1 rengine_celery-beat_1 rengine_redis_1 rengine_tor_1 rengine_proxy_1`
- All Rengine containers was renamed a little while ago. **Example:**  `rengine_web_1` is now `rengine-web-1`, so:  `_` is now `-`
- Due to these outdated lines, uninstalling Reingine will not work!

**Renaming line 14**
![image](https://github.com/yogeshojha/rengine/assets/106466414/43a4da54-ef39-4cea-8c6f-17e2b4a2063e)

**Docker system prune - to be sure for a Rengine fresh reinstall**

`sudo make prune`

```
make[1]: Entering directory '/home/myusername/bin/rengine'
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml stop db web proxy redis celery celery-beat
make[1]: Leaving directory '/home/myusername/bin/rengine'
make[1]: Entering directory '/home/myusername/bin/rengine'
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml rm -f db web proxy redis celery celery-beat
No stopped containers
make[1]: Leaving directory '/home/myusername/bin/rengine'
Deleted Volumes:
dcd8d8ad49d89bf11d58335cbaffa58a0f2987caf7f39a14fa4536c408f524f5
ee60970e92641c85a6f03e41afbadacfef5449e85b48f94c1b8e58f55b2440a1
```

Total reclaimed space: 6.105kB

`docker system prune`

![image](https://github.com/yogeshojha/rengine/assets/106466414/f87760a2-4725-45a8-b11d-94cfba1f2bce)

**Remove Rengine - for a fresh reinstall**

**Check Docker volumes**
`docker volume ls`

**Delete all existent volumes**
`docker volume prune`

**Check Docker containers**
`docker ps`

**Delete all containers**
`docker rm -f $(docker ps -a -q)`

**Remove old Rengine folder**
`cd .. && sudo rm -rf rengine`

**Reinstall Rengine - Fresh install**
`git clone https://github.com/yogeshojha/rengine && cd rengine`

**Edit .env**
`nano .env`
- Changed POSTGRES_USER & POSTGRES_PASSWORD values

`Generate certificates`
`sudo make certs`

**Install Rengine**

- Looks like fresh install Reingine installs 2.0.2 instead of 2.0.3

sudo ./install
![image](https://github.com/yogeshojha/rengine/assets/106466414/682b92ed-6a92-4941-9927-4e2b190dc88a)

**Rengine Installed - but errors**

![image](https://github.com/yogeshojha/rengine/assets/106466414/3267c801-ad45-4887-b76e-92fba8cd4836)

**Full errors output from istall - via terminal**

```
WARNINGS:
startScan.EndPoint.techs: (fields.W340) null has no effect on ManyToManyField.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "db" (172.25.0.3), port 5432 failed: FATAL:  password authentication failed for user "myusername"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 26, in <module>
    main()
  File "/usr/src/app/manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 397, in execute
    self.check_migrations()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "db" (172.25.0.3), port 5432 failed: FATAL:  password authentication failed for user "myusername"

make: *** [Makefile:28: username] Error 1

Thank you for installing reNgine, happy recon!!
```

**It seems that the error https://github.com/yogeshojha/rengine/issues/972 has reappeared on the scene**  

**Restart containers**
`make restart`
![image](https://github.com/yogeshojha/rengine/assets/106466414/297245b5-ce13-453b-87e7-43ecfdc4af90)

**List docker containers**
`docker ps`
![image](https://github.com/yogeshojha/rengine/assets/106466414/08a062e8-159d-44f3-b97c-76cb2f39c0fe)

**Browser access Rengine** 
https://127.0.0.1
![image](https://github.com/yogeshojha/rengine/assets/106466414/5588a7f6-28b2-4c51-b5fa-933370b102f9)

Of course, I checked and have all the Rengine requirements installed. Plus it's reinstall, so it was installed on the same OS with no problems!

I have tried fresh install several times, each time the same problem! I even tried without changing username and password in .env, same error every time!

I can't seem to reinstall Rengine!

### Expected Behavior

Install Rengine

### Steps To Reproduce

Explained above.

### Environment

```markdown
- reNgine: Trying to reinstall Rengine
- OS: Ubuntu 22.04.3 LTS
- Python: Python 3.10.12
- Docker Engine: Docker version 25.0.2, build 29cf629
- Docker Compose: Docker Compose version v2.5.0
- Browser: Firefox / Chrome - N/A
```

**Comment by carboncrystal** [comment]
**@Solved** - But please do not close until uninstall.sh is updated. There are a lot of BUGs here!

**unistall.sh** - has bugs, so uninstalling will not work correctly, either containers, volumes, networks or old images will be retained.

**Solution**: 

1. docker commands to list what's left from Rengine, commands like `docker ps`, `docker volume ls`, `docker images`, `docker network ls`.
2. manually stop what's left from Rengine: `docker stop [container_name]`
3. delete what is left of Rengine (container, volume, networks, images): `docker rm [container_name]`, `docker volume rm [volume_name]`, `docker network rm [rengine_network_name]`, `docker rmi [RENGINE IMAGE_ID1] [RENGINE IMAGE_ID2]` etc.
4. **but don't forget to somehow delete the containers created by Docker (read below why)!**

**Don't delete containers created by Docker before install / reinstall Rengine** 
The new Docker uppdate creates 2 volumes by default, if you delete them before installing / reinstall Rengine, this is because you want to do "Docker clean", because Rengine doesn't install correctly and you get errors, Docker will automatically create them again when you install / reinstall Rengine and so Rengine won't install correctly, it will omit to ask you in the terminal username, email and password (even if they are set to .env). And these volumes created by Docker will interfere with "null"!. 
**You'll get errors like:**  
- [Makefile:28: username] Error 1)
- WARNINGS: startScan.EndPoint.techs: (fields.W340) **null has no effect** on ManyToManyField.

So before install / reinstall Rengine: check default Docker volumes are present:
`docker volume ls`
![Screenshot from 2024-02-09 10-05-58](https://github.com/yogeshojha/rengine/assets/106466414/00bbffc1-a670-4d1c-b26f-c7a61e225dda)

docker volume inspect [volume-name]
![Screenshot from 2024-02-09 08-28-44](https://github.com/yogeshojha/rengine/assets/106466414/07335fac-a758-474a-9e32-4552eb6009e4)


- From here come the errors with "null", [Makefile:28: username] Error 1), WARNINGS: startScan.EndPoint.techs: (fields.W340), login - user connection to DB and probably other errors. 
- Because the default Docker volumes are created during Rengine installation! They must be present before installation, and if you reinstall Rengine, old containers, network, volumes and Rengine images must be manually deleted! Rengine's unistall.sh omits some of them (BUG).

**Comment by psyray** [comment]
@carboncrystal Could you provide a PR with the modifications ?

**Comment by yogeshojha** [comment]
Hi @carboncrystal 

This has been fixed in the above PR

> reNgine uninstall script has been optimized to perform operations such as stopping the container, deleting the containers, and volumes that are only related to reNgine. This will also remove build cache objects related to reNgine installation.
