### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by null-ref-0000** [yogeshojha/rengine#1407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

rengine-celery-1 container is throwing an error

### Expected Behavior

rengine-celery-1 container should start with out error

### Steps To Reproduce

Checkout code from master branch 

### Environment

```markdown
- reNgine: 2.1.3
- OS: Debian 12
- Python: 3.11.2
- Docker Engine: 26.1.2
- Docker Compose: v2.5.0
- Browser: n/a
```

### Anything else?

 pikepdf._core | pikepdf C++ to Python logger bridge initialized
celery-1       | pikepdf._core | pikepdf C++ to Python logger bridge initialized
celery-1       | pikepdf._core | pikepdf C++ to Python logger bridge initialized
celery-1       | pikepdf._core | pikepdf C++ to Python logger bridge initialized
celery-1       | pikepdf._core | pikepdf C++ to Python logger bridge initialized
celery-1       | pikepdf._core | pikepdf C++ to Python logger bridge initialized
celery-1       | pikepdf._core | pikepdf C++ to Python logger bridge initialized
celery-1       | pikepdf._core | pikepdf C++ to Python logger bridge initialized
celery-1       | Usage: celery [OPTIONS] COMMAND [ARGS]...
celery-1       | Try 'celery --help' for help.
celery-1       | 
celery-1       | Error: Invalid value for '-A' / '--app': 
celery-1       | Unable to load celery application.
celery-1       | While trying to load the module reNgine.tasks the following error occurred:
celery-1       | Traceback (most recent call last):
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/app/utils.py", line 383, in find_app
celery-1       |     sym = symbol_by_name(app, imp=imp)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/kombu/utils/imports.py", line 64, in symbol_by_name
celery-1       |     return getattr(module, cls_name) if cls_name else module
celery-1       | AttributeError: module 'reNgine' has no attribute 'tasks'
celery-1       | 
celery-1       | During handling of the above exception, another exception occurred:
celery-1       | 
celery-1       | Traceback (most recent call last):
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/bin/celery.py", line 58, in convert
celery-1       |     return find_app(value)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/app/utils.py", line 386, in find_app
celery-1       |     sym = imp(app)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/utils/imports.py", line 109, in import_from_cwd
celery-1       |     return imp(module, package=package)
celery-1       |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
celery-1       |     return _bootstrap._gcd_import(name[level:], package, level)
celery-1       |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
celery-1       |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
celery-1       |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
celery-1       |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
celery-1       |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
celery-1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
celery-1       |   File "/usr/src/app/reNgine/tasks.py", line 32, in <module>
celery-1       |     from reNgine.llm import *
celery-1       |   File "/usr/src/app/reNgine/llm.py", line 6, in <module>
celery-1       |     from langchain_community.llms import Ollama
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langchain_community/llms/__init__.py", line 24, in <module>
celery-1       |     from langchain_core.language_models.llms import BaseLLM
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/__init__.py", line 48, in <module>
celery-1       |     from langchain_core.language_models.chat_models import BaseChatModel, SimpleChatModel
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 28, in <module>
celery-1       |     from langchain_core.callbacks import (
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langchain_core/callbacks/__init__.py", line 23, in <module>
celery-1       |     from langchain_core.callbacks.manager import (
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langchain_core/callbacks/manager.py", line 29, in <module>
celery-1       |     from langsmith.run_helpers import get_run_tree_context
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langsmith/run_helpers.py", line 41, in <module>
celery-1       |     from langsmith import client as ls_client
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langsmith/client.py", line 55, in <module>
celery-1       |     from langsmith import env as ls_env
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langsmith/env/__init__.py", line 3, in <module>
celery-1       |     from langsmith.env._runtime_env import (
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langsmith/env/_runtime_env.py", line 10, in <module>
celery-1       |     from langsmith.utils import get_docker_compose_command
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/langsmith/utils.py", line 35, in <module>
celery-1       |     import httpx
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/httpx/__init__.py", line 2, in <module>
celery-1       |     from ._api import *
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/httpx/_api.py", line 6, in <module>
celery-1       |     from ._client import Client
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 32, in <module>
celery-1       |     from ._transports.default import AsyncHTTPTransport, HTTPTransport
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/__init__.py", line 3, in <module>
celery-1       |     from .default import *
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 33, in <module>
celery-1       |     import httpcore
celery-1       | ModuleNotFoundError: No module named 'httpcore'

**Comment by null-ref-0000** [comment]
My fork of master was behind a couple commits.
