### ISSUE TITLE
bug: Web error when H1 API key is missing

### ISSUE THREAD

**Issue by ba0f3** [yogeshojha/rengine#1426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Server error 500 after login to dashboard after update to version 2.2.0
```
web_1          | django.request | Internal Server Error: /
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/src/app/dashboard/views.py", line 420, in onboarding
web_1          |     context['hackerone_key'] = HackerOneAPIKey.objects.first().key # <===
web_1          | AttributeError: 'NoneType' object has no attribute 'key'
```

### Expected Behavior

It should redirect to dashboard

### Steps To Reproduce

- Update to version 2.2.0
- start containers 
- login to dashboard

### Environment

```markdown
- reNgine: 2.2.0
- OS: Linux
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by ipsecc** [comment]
same as me

**Comment by yogeshojha** [comment]
Hi @ba0f3 @ipsecc such a silly mistake ;p

I have fixed this now, please pull the latest branch.

Thank you!
