### ISSUE TITLE
bug: <Vulnerability scanFailed>

### ISSUE THREAD

**Issue by ipsecc** [yogeshojha/rengine#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Error: TimeoutError('Timeout reading from socket')**

![image](https://github.com/user-attachments/assets/303451d9-2083-460a-a712-77c3b328a73f)

### Expected Behavior

Vulnerability scan

### Steps To Reproduce

```
celery-1       | vulnerability_scan                 | ERROR | Timeout reading from socket
celery-1       | Traceback (most recent call last):
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/socket.py", line 65, in _read_from_socket
celery-1       |     data = self._sock.recv(socket_read_size)
celery-1       | TimeoutError: timed out
celery-1       |
celery-1       | During handling of the above exception, another exception occurred:
celery-1       |
celery-1       | Traceback (most recent call last):
celery-1       |   File "/usr/src/app/reNgine/celery_custom_task.py", line 129, in __call__
celery-1       |     self.result = self.run(*args, **kwargs)
celery-1       |   File "/usr/src/app/reNgine/tasks.py", line 2077, in vulnerability_scan
celery-1       |     while not job.ready():
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 652, in ready
celery-1       |     return all(result.ready() for result in self.results)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 652, in <genexpr>
celery-1       |     return all(result.ready() for result in self.results)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 347, in ready
celery-1       |     return self.state in self.backend.READY_STATES
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 503, in state
celery-1       |     return self._get_task_meta()['status']
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 442, in _get_task_meta
celery-1       |     return self._maybe_set_cache(self.backend.get_task_meta(self.id))
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/backends/base.py", line 608, in get_task_meta
celery-1       |     meta = self._get_task_meta_for(task_id)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/backends/base.py", line 995, in _get_task_meta_for
celery-1       |     meta = self.get(self.get_key_for_task(task_id))
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/backends/redis.py", line 376, in get
celery-1       |     return self.client.get(key)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/commands/core.py", line 1830, in get
celery-1       |     return self.execute_command("GET", name)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 543, in execute_command
celery-1       |     return conn.retry.call_with_retry(
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/retry.py", line 49, in call_with_retry
celery-1       |     fail(error)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 547, in <lambda>
celery-1       |     lambda error: self._disconnect_raise(conn, error),
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 533, in _disconnect_raise
celery-1       |     raise error
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/retry.py", line 46, in call_with_retry
celery-1       |     return do()
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 544, in <lambda>
celery-1       |     lambda: self._send_command_parse_response(
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 520, in _send_command_parse_response
celery-1       |     return self.parse_response(conn, command_name, **options)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 560, in parse_response
celery-1       |     response = connection.read_response()
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 512, in read_response
celery-1       |     response = self._parser.read_response(disable_decoding=disable_decoding)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/resp2.py", line 15, in read_response
celery-1       |     result = self._read_response(disable_decoding=disable_decoding)
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/resp2.py", line 25, in _read_response
celery-1       |     raw = self._buffer.readline()
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/socket.py", line 115, in readline
celery-1       |     self._read_from_socket()
celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/socket.py", line 78, in _read_from_socket
celery-1       |     raise TimeoutError("Timeout reading from socket")
celery-1       | redis.exceptions.TimeoutError: Timeout reading from socket
```

### Environment

```markdown
- reNgine: v2.2.0
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by yogeshojha** [comment]
@ipsecc is your target accesible?

**Comment by ipsecc** [comment]
Thanks for reply @yogeshojha , yes, it is accessible. Some nuclei tasks continue to scan after the error occurred.
![image](https://github.com/user-attachments/assets/2e32632e-d309-477a-99da-9d942924cb2b)

**Comment by Manhatthien-98** [comment]
> ### Có vấn đề nào hiện hữu ở đây không?
> * [x] Tôi đã tìm kiếm các vấn đề hiện có
> 
> ### Hành vi hiện tại
> **Lỗi: TimeoutError('Hết thời gian đọc từ ổ cắm')**
> 
> ![image](https://github.com/user-attachments/assets/303451d9-2083-460a-a712-77c3b328a73f)
> 
> ### Hành vi mong đợi
> Quét lỗ hổng
> 
> ### Các bước để sinh sản
> ```
> celery-1       | vulnerability_scan                 | ERROR | Timeout reading from socket
> celery-1       | Traceback (most recent call last):
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/socket.py", line 65, in _read_from_socket
> celery-1       |     data = self._sock.recv(socket_read_size)
> celery-1       | TimeoutError: timed out
> celery-1       |
> celery-1       | During handling of the above exception, another exception occurred:
> celery-1       |
> celery-1       | Traceback (most recent call last):
> celery-1       |   File "/usr/src/app/reNgine/celery_custom_task.py", line 129, in __call__
> celery-1       |     self.result = self.run(*args, **kwargs)
> celery-1       |   File "/usr/src/app/reNgine/tasks.py", line 2077, in vulnerability_scan
> celery-1       |     while not job.ready():
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 652, in ready
> celery-1       |     return all(result.ready() for result in self.results)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 652, in <genexpr>
> celery-1       |     return all(result.ready() for result in self.results)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 347, in ready
> celery-1       |     return self.state in self.backend.READY_STATES
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 503, in state
> celery-1       |     return self._get_task_meta()['status']
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/result.py", line 442, in _get_task_meta
> celery-1       |     return self._maybe_set_cache(self.backend.get_task_meta(self.id))
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/backends/base.py", line 608, in get_task_meta
> celery-1       |     meta = self._get_task_meta_for(task_id)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/backends/base.py", line 995, in _get_task_meta_for
> celery-1       |     meta = self.get(self.get_key_for_task(task_id))
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/celery/backends/redis.py", line 376, in get
> celery-1       |     return self.client.get(key)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/commands/core.py", line 1830, in get
> celery-1       |     return self.execute_command("GET", name)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 543, in execute_command
> celery-1       |     return conn.retry.call_with_retry(
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/retry.py", line 49, in call_with_retry
> celery-1       |     fail(error)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 547, in <lambda>
> celery-1       |     lambda error: self._disconnect_raise(conn, error),
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 533, in _disconnect_raise
> celery-1       |     raise error
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/retry.py", line 46, in call_with_retry
> celery-1       |     return do()
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 544, in <lambda>
> celery-1       |     lambda: self._send_command_parse_response(
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 520, in _send_command_parse_response
> celery-1       |     return self.parse_response(conn, command_name, **options)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 560, in parse_response
> celery-1       |     response = connection.read_response()
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 512, in read_response
> celery-1       |     response = self._parser.read_response(disable_decoding=disable_decoding)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/resp2.py", line 15, in read_response
> celery-1       |     result = self._read_response(disable_decoding=disable_decoding)
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/resp2.py", line 25, in _read_response
> celery-1       |     raw = self._buffer.readline()
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/socket.py", line 115, in readline
> celery-1       |     self._read_from_socket()
> celery-1       |   File "/usr/local/lib/python3.10/dist-packages/redis/_parsers/socket.py", line 78, in _read_from_socket
> celery-1       |     raise TimeoutError("Timeout reading from socket")
> celery-1       | redis.exceptions.TimeoutError: Timeout reading from socket
> ```
> 
> ### Môi trường
> - reNgine: v2.2.0
> - OS: 
> - Python: 
> - Docker Engine: 
> - Docker Compose: 
> - Browser:
> ### Còn gì nữa không?
> _Không có phản hồi_

https://github.com/yogeshojha/rengine/issues/1448#issue-2553941938
https://github.com/yogeshojha/rengine/issues/1448
