### ISSUE TITLE
bug: Unable to Add subfinder API keys

### ISSUE THREAD

**Issue by rajesh457** [yogeshojha/rengine#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Gives **Server Error (500)** when trying to add subfinder API keys

### Expected Behavior

200 OK

### Steps To Reproduce

1. Go to https://<VPS:IP>/scanEngine/default/tool_settings

2. Try to add any API key for subfinder

3. see the error

### Environment

```markdown
- reNgine: Latest
- OS: UBUNTU 24
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

![image](https://github.com/user-attachments/assets/1c8aa7ed-edf2-4a83-93ee-adc62c1497ac)

**Comment by ipsecc** [comment]
you can modify `./volumes/rengine_tool_config/_data/subfinder/provider-config.yaml`, it will work.

**Comment by rajesh457** [comment]
Hi @ipsecc,
Where i can find that path, would you please give the exact path where I can modify the `provider-config.yaml` file

**Comment by ipsecc** [comment]
hi @rajesh457 ,use `find / -name "provider-config.yaml" 2>/dev/null`, you will find it

**Comment by breaking153** [comment]
same issue here, did you find a way to make subfinder work?

**Comment by isira-adithya** [comment]
When debugging, I encountered the following error:

```
web-1          | June 29, 2025 - 14:04:09
web-1          | Django version 3.2.23, using settings 'reNgine.settings'
web-1          | Starting development server at http://0.0.0.0:8000/
web-1          | Quit the server with CONTROL-C.
web-1          | django.request | Internal Server Error: /scanEngine/default/tool_settings
web-1          | Traceback (most recent call last):
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
web-1          |     response = get_response(request)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
web-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/rolepermissions/decorators.py", line 21, in wrapper
web-1          |     return dispatch(request, *args, **kwargs)
web-1          |   File "/usr/src/app/scanEngine/views.py", line 243, in tool_specific_settings
web-1          |     with open('/root/.config/subfinder/config.yaml', "w") as fhandle:
web-1          | FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/subfinder/config.yaml'
web-1          | django.server | "POST /scanEngine/default/tool_settings HTTP/1.0" 500 80904
```

I was able to resolve this by manually creating the missing `~/.config/subfinder/` directory inside the rengine container.

**Steps:**
- Run `docker ps` to list running containers.
- Find the container ID of `docker.pkg.github.com/yogeshojha/rengine/rengine:latest`.
- Execute: `docker exec [CONTAINER_ID_HERE] mkdir -p ~/.config/subfinder/`


After doing this, saving the subfinder config works as expected.
