### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by gopinath6** [yogeshojha/rengine#169]
Am trying  to install through sourcecode in windows 10 home edition.Getting below error when trying  to create user

D:\Dropbox\bug\Asus\Web\Tools\OSINT\rengine>python manage.py createsuperuser
Traceback (most recent call last):
  File "D:\Dropbox\bug\Asus\Web\Tools\OSINT\rengine\reNgine\init.py", line 24, in first_run
    secret = open(secret_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/app\\secret'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Python38\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Python38\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "C:\Python38\lib\site-packages\django\conf\__init__.py", line 76, in __getattr__
    self._setup(name)
  File "C:\Python38\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python38\lib\site-packages\django\conf\__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Dropbox\bug\Asus\Web\Tools\OSINT\rengine\reNgine\settings.py", line 14, in <module>
    SECRET_KEY = first_run(SECRET_FILE, BASE_DIR)
  File "D:\Dropbox\bug\Asus\Web\Tools\OSINT\rengine\reNgine\init.py", line 28, in first_run
    raise Exception('Secret file generation failed' % secret_file)
TypeError: not all arguments converted during string formatting

**Comment by JoshuaMart** [comment]
Hi,
Seems normal, you try to execute the command outside the docker, outside the project is installed with docker

If you try without, not sure we can help you, especially with so little information.
