### ISSUE TITLE
Bug - make build failed with undefined: gologger.Errorf

### ISSUE THREAD

**Issue by puzanov** [yogeshojha/rengine#303]
### Issue Summary

httpx required gologger v1.0.1, but v1.1.2 installed instead where Errorf func were removed

### Steps to Reproduce

Run  `make build`

### Technical details

Probably another pkg requires newer gologger 
![image](https://user-images.githubusercontent.com/91070/102880107-0626ca80-4475-11eb-9230-e5c560709974.png)

```
Step 13/25 : RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx
 ---> Running in 14eceeedcd17
go: downloading github.com/projectdiscovery/httpx v1.0.3
go: found github.com/projectdiscovery/httpx/cmd/httpx in github.com/projectdiscovery/httpx v1.0.3
go: downloading github.com/projectdiscovery/gologger v1.0.1
go: downloading github.com/remeh/sizedwaitgroup v1.0.0
go: downloading github.com/projectdiscovery/fdmax v0.0.2
go: downloading github.com/projectdiscovery/clistats v0.0.5
go: downloading github.com/projectdiscovery/mapcidr v0.0.4
go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
go: downloading github.com/projectdiscovery/rawhttp v0.0.4
go: downloading github.com/projectdiscovery/hmap v0.0.1
go: downloading golang.org/x/net v0.0.0-20201110031124-69a78807bb2b
go: downloading github.com/microcosm-cc/bluemonday v1.0.4
go: downloading github.com/projectdiscovery/fastdialer v0.0.1
go: downloading go.uber.org/atomic v1.7.0
go: downloading golang.org/x/text v0.3.4
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/projectdiscovery/cdncheck v0.0.1
go: downloading github.com/hbakhtiyor/strsim v0.0.0-20190107154042-4d2bbb273edf
go: downloading github.com/projectdiscovery/retryabledns v1.0.5
go: downloading github.com/syndtr/goleveldb v1.0.0
go: downloading github.com/chris-ramon/douceur v0.2.0
go: downloading github.com/yl2chen/cidranger v1.0.0
go: downloading github.com/projectdiscovery/retryablehttp-go v1.0.1
go: downloading github.com/miekg/dns v1.1.29
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: downloading github.com/aymerick/douceur v0.2.0
go: downloading github.com/gorilla/css v1.0.0
go: downloading golang.org/x/sys v0.0.0-20201113233024-12cec1faf1ba
go: downloading golang.org/x/crypto v0.0.0-20201112155050-0c6587e931a9
go: github.com/golang/snappy upgrade => v0.0.2
go: github.com/miekg/dns upgrade => v1.1.35
go: golang.org/x/net upgrade => v0.0.0-20201216054612-986b41b23924
go: github.com/projectdiscovery/fdmax upgrade => v0.0.3
go: github.com/yl2chen/cidranger upgrade => v1.0.2
go: golang.org/x/text upgrade => v0.3.4
go: github.com/projectdiscovery/fastdialer upgrade => v0.0.2
go: golang.org/x/crypto upgrade => v0.0.0-20201221181555-eec23a3978ad
go: golang.org/x/sys upgrade => v0.0.0-20201221093633-bc327ba9c2f0
go: github.com/logrusorgru/aurora upgrade => v2.0.3+incompatible
go: github.com/projectdiscovery/gologger upgrade => v1.1.2
go: github.com/projectdiscovery/clistats upgrade => v0.0.7
go: downloading github.com/projectdiscovery/gologger v1.1.2
go: downloading golang.org/x/net v0.0.0-20201216054612-986b41b23924
go: downloading github.com/projectdiscovery/fastdialer v0.0.2
go: downloading github.com/projectdiscovery/fdmax v0.0.3
go: downloading github.com/yl2chen/cidranger v1.0.2
go: downloading github.com/projectdiscovery/clistats v0.0.7
go: downloading github.com/golang/snappy v0.0.2
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/dimchansky/utfbom v1.1.1
go: downloading github.com/miekg/dns v1.1.35
go: downloading golang.org/x/sys v0.0.0-20201221093633-bc327ba9c2f0
go: downloading github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: downloading github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
go: downloading golang.org/x/crypto v0.0.0-20201221181555-eec23a3978ad
go: github.com/modern-go/reflect2 upgrade => v1.0.1
go: github.com/modern-go/concurrent upgrade => v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.1
github.com/projectdiscovery/gologger/levels
golang.org/x/sys/internal/unsafeheader
github.com/projectdiscovery/httpx/common/customheader
golang.org/x/net/html/atom
golang.org/x/net/internal/iana
github.com/projectdiscovery/httpx/common/slice
golang.org/x/text/encoding/internal/identifier
github.com/syndtr/goleveldb/leveldb/comparer
github.com/projectdiscovery/hmap/store/cache
github.com/golang/snappy
golang.org/x/sys/unix
github.com/dimchansky/utfbom
golang.org/x/text/transform
github.com/modern-go/concurrent
github.com/logrusorgru/aurora
github.com/projectdiscovery/gologger/writer
go.uber.org/atomic
github.com/syndtr/goleveldb/leveldb/util
github.com/modern-go/reflect2
github.com/syndtr/goleveldb/leveldb/storage
github.com/hbakhtiyor/strsim
github.com/aymerick/douceur/css
github.com/projectdiscovery/clistats
github.com/syndtr/goleveldb/leveldb/cache
github.com/syndtr/goleveldb/leveldb/filter
github.com/gorilla/css/scanner
golang.org/x/net/html
github.com/yl2chen/cidranger/net
github.com/syndtr/goleveldb/leveldb/opt
github.com/syndtr/goleveldb/leveldb/errors
github.com/chris-ramon/douceur/parser
github.com/yl2chen/cidranger
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
golang.org/x/crypto/ed25519
golang.org/x/net/bpf
github.com/projectdiscovery/retryablehttp-go
github.com/projectdiscovery/cdncheck
github.com/projectdiscovery/rawhttp/client
github.com/syndtr/goleveldb/leveldb/memdb
github.com/syndtr/goleveldb/leveldb/table
github.com/rs/xid
golang.org/x/text/unicode/bidi
github.com/projectdiscovery/httpx/common/httputilz
github.com/projectdiscovery/rawhttp/clientpipeline
golang.org/x/text/unicode/norm
golang.org/x/net/http2/hpack
github.com/syndtr/goleveldb/leveldb
golang.org/x/text/secure/bidirule
github.com/projectdiscovery/fdmax
golang.org/x/net/internal/socket
github.com/projectdiscovery/fdmax/autofdmax
github.com/json-iterator/go
golang.org/x/text/encoding
github.com/projectdiscovery/httpx/common/fileutil
github.com/projectdiscovery/httpx/common/iputil
github.com/microcosm-cc/bluemonday
github.com/projectdiscovery/httpx/common/stringz
golang.org/x/text/encoding/internal
github.com/projectdiscovery/mapcidr
github.com/projectdiscovery/rawhttp
golang.org/x/text/encoding/simplifiedchinese
golang.org/x/net/ipv4
golang.org/x/net/ipv6
golang.org/x/net/idna
golang.org/x/text/encoding/traditionalchinese
github.com/remeh/sizedwaitgroup
github.com/miekg/dns
golang.org/x/net/http/httpguts
golang.org/x/net/http2
github.com/projectdiscovery/hmap/store/disk
github.com/projectdiscovery/hmap/store/hybrid
github.com/projectdiscovery/gologger/formatter
github.com/projectdiscovery/gologger
github.com/projectdiscovery/retryabledns
github.com/projectdiscovery/fastdialer/fastdialer
github.com/projectdiscovery/httpx/common/httpx
# github.com/projectdiscovery/httpx/common/httpx
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.3/common/httpx/http2.go:41:4: undefined: gologger.Errorf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.3/common/httpx/http2.go:61:3: undefined: gologger.Errorf
The command '/bin/sh -c GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx' returned a non-zero code: 2
[7257] Failed to execute script docker-compose
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 303, in build
  File "compose/project.py", line 403, in build
  File "compose/project.py", line 385, in build_service
  File "compose/service.py", line 1110, in build
  File "compose/progress_stream.py", line 25, in stream_output
  File "compose/utils.py", line 61, in split_buffer
  File "compose/utils.py", line 37, in stream_as_text
  File "compose/service.py", line 1818, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpkgkz51gz'
Makefile:25: recipe for target 'build' failed
make: *** [build] Error 255
```

**Comment by thau0x01** [comment]
facing the same issue. 

Thank you all rengine devs for the amazing tool!

**Comment by jarvisuser90** [comment]
Same problem.

**Comment by TerickJojo** [comment]
same

**Comment by AlTahish** [comment]
same

**Comment by mastomii** [comment]
I was successfully installed by modifying the `Dockerfile`

From:

```
RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx

RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder \
    github.com/projectdiscovery/nuclei/v2/cmd/nuclei \
    github.com/lc/gau \
    github.com/projectdiscovery/naabu/cmd/naabu
```

To:

```
RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx

RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/subfinder \
    github.com/projectdiscovery/nuclei \
    github.com/lc/gau \
    github.com/projectdiscovery/naabu
```

**Comment by Kun19** [comment]
A workaround is to remove the -u flag in the Dockerfile to avoid upgrading gologger from v1.0.1 to v1.1.2.

```
diff --git a/Dockerfile b/Dockerfile
index 1fc6d9f..5c45217 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -30,9 +30,9 @@ ENV PATH="${PATH}:${GOPATH}/bin"
 # Download Go packages
 RUN go get -u github.com/tomnomnom/assetfinder github.com/hakluke/hakrawler
 
-RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx
+RUN GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx
 
-RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder \
+RUN GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder \
     github.com/projectdiscovery/nuclei/v2/cmd/nuclei \
     github.com/lc/gau \
     github.com/projectdiscovery/naabu/cmd/naabu
```

**Comment by AlTahish** [comment]
Another Problem After Editing Dockerfile:
o get github.com/projectdiscovery/httpx/cmd/httpx: module github.com/projectdiscovery/httpx/cmd/httpx: Get "https://proxy.golang.org/github.com/projectdiscovery/httpx/cmd/httpx/@v/list": dial tcp: lookup proxy.golang.org on 192.168.191.2:53: read udp 172.17.0.2:46566->192.168.191.2:53: i/o timeout                 
The command '/bin/sh -c GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx' returned a non-zero code: 1                                     
ERROR: Service 'web' failed to build                                                                                                                          
make: *** [Makefile:25: build] Error 1

**Comment by AlTahish** [comment]
Another Problem After Editing Dockerfile:
`o get github.com/projectdiscovery/httpx/cmd/httpx: module github.com/projectdiscovery/httpx/cmd/httpx: Get "https://proxy.golang.org/github.com/projectdiscovery/httpx/cmd/httpx/@v/list": dial tcp: lookup proxy.golang.org on 192.168.191.2:53: read udp 172.17.0.2:46566->192.168.191.2:53: i/o timeout                 
The command '/bin/sh -c GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx' returned a non-zero code: 1                                     
ERROR: Service 'web' failed to build                                                                                                                          
make: *** [Makefile:25: build] Error 1
`

**Comment by puzanov** [comment]
@AlTahish 

Seems that you have a connection problem on your box: `dial tcp: lookup proxy.golang.org on 192.168.191.2:53: read udp 172.17.0.2:46566->192.168.191.2:53: i/o timeout The command`

**Comment by puzanov** [comment]
@Kun19 your solution solved the problem. Consider to send PR.

**Comment by AlTahish** [comment]
@puzanov

**Comment by b0tzone** [comment]
> A workaround is to remove the -u flag in the Dockerfile to avoid upgrading gologger from v1.0.1 to v1.1.2.
> 
> ```
> diff --git a/Dockerfile b/Dockerfile
> index 1fc6d9f..5c45217 100644
> --- a/Dockerfile
> +++ b/Dockerfile
> @@ -30,9 +30,9 @@ ENV PATH="${PATH}:${GOPATH}/bin"
>  # Download Go packages
>  RUN go get -u github.com/tomnomnom/assetfinder github.com/hakluke/hakrawler
>  
> -RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx
> +RUN GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx
>  
> -RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder \
> +RUN GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder \
>      github.com/projectdiscovery/nuclei/v2/cmd/nuclei \
>      github.com/lc/gau \
>      github.com/projectdiscovery/naabu/cmd/naabu
> ```

Thank you!  This is working for me.

**Comment by yogeshojha** [comment]
Sorry guys, I was away from reNgine for a while. Thank you @Kun19 for your PR. I have merged it, fixes the issue now.
