### ISSUE TITLE
Manage.py migrate

### ISSUE THREAD

**Issue by permis20182018** [yogeshojha/rengine#525]
Hello , 

First thanks for that awesome work , 

i get and error everytime i run python3 manage.py migrate ---->

```
`Traceback (most recent call last):
  File "manage.py", line 14, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    main()
  File "manage.py", line 20, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?`
```

the rengine failed to scan , its start scaning subdomain succefully but its fails after that 

Any clue for  a Fix 

after installing some missing module manully using pip isnatll 

i get another error 

Traceback (most recent call last):
  File "/home/permis201s018_gmail_com/rengine/web/reNgine/init.py", line 24, in first_run
    secret = open(secret_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/secret'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    main()
  File "manage.py", line 21, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/permis20182018_gmail_com/rengine/web/reNgine/settings.py", line 14, in <module>
    SECRET_KEY = first_run(SECRET_FILE, BASE_DIR)
  File "/home/permis20s18_gmail_com/rengine/web/reNgine/init.py", line 28, in first_run
    raise Exception('Secret file generation failed' % secret_file)
TypeError: not all arguments converted during string formatting
```

**Comment by TerickJojo** [comment]
@permis20182018 Do u fix it?
